### ISSUE TITLE
Regex for exclusive users namespaces catches too many strings

### ISSUE THREAD

**Issue by almereyda** [turt2live/matrix-dimension#227]
After installing dimension with the standard procedure, it blocks all new user registrations, due to a very wide regex formulated in

![bildschirmfoto von 2018-11-01 20-11-49](https://user-images.githubusercontent.com/1645308/47875132-0b000e80-de16-11e8-87d3-c56ecc729b8c.png)

```
id: dimension-<redacted>
url: https://connect.allmende.io/_matrix/appservice/r0
as_token: <redacted>
hs_token: <redacted>
sender_localpart: .
namespaces:
  users:
    - exclusive: true
      regex: '@..*'
  aliases: []
  rooms: []
```

What would be a sane default here for the @allmende home server? https://github.com/tulir/mautrix-telegram/issues/242#issuecomment-434151742 suggests to go for something like

    @dimension-.+:matrix.allmende.io
