### ISSUE TITLE
apache reverse proxy - unable to pass certificates to "docker" - UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by BlackWolfDEsign** [turt2live/matrix-dimension#317]
Hi i want to use docker and an apache reverse proxy to provide dimension. My Docker container crashes constantly because the container "does not receive the certificates." ;/ It is possible to store the certificates in the container manually?

error:
```
Dec-3-2019 20:37:02.766 +00:00 error [BotSdk-MatrixLiteClient (REQ-1)] unable to verify the first certificate
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
{ Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

following my configs:
apache matrix conf:
```
<VirtualHost *:80>
        ServerName dimension.[DOMAIN]
        RewriteEngine on
        RewriteCond %{HTTPS} !=on
        RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [R=301,L]
        ProxyPass / https://127.0.0.1:8184/
        ProxyPassReverse / https://127.0.0.1:8184/
</VirtualHost>

<VirtualHost *:443>
        SSLEngine on
        ServerName dimension.[DOMAIN]
        #ProxyPass /.well-known/ !
        ProxyPass / https://127.0.0.1:8184/
        ProxyPassReverse / https://127.0.0.1:8184/
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyVia Full
        #SSLProxyEngine on
        #ProxyRequests on
        ProxyPreserveHost On
        ProxyErrorOverride On
        #ProxyAddHeaders On
        #RequestHeader set X-Forwarded-Proto "https"
        #RequestHeader set "X-RP-UNIQUE-ID"      "%{UNIQUE_ID}e"
        #RequestHeader set "X-RP-REMOTE-USER"    "%{REMOTE_USER}e"
        RequestHeader set "X-RP-SSL-PROTOCOL"   "%{SSL_PROTOCOL}s"
        #RequestHeader set "X-RP-SSL-CIPHER"     "%{SSL_CIPHER}s"
        #RemoteIPHeader X-Forwarded-For
        #RemoteIPTrustedProxy 127.0.0.1
        SSLCertificateFile /etc/letsencrypt/live/dimension.[DOMAIN]/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/dimension.[DOMAIN]/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/dimension.[DOMAIN]/chain.pem
</VirtualHost>
```
apache chat conf:
```
<VirtualHost *:80>
        ServerName chat.[DOMAIN]
        RewriteEngine on

        RewriteCond %{HTTPS} !=on
        RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [R=301,L]

        AllowEncodedSlashes NoDecode

        #ProxyPass /riot http://127.0.0.1:8888/
        #ProxyPassReverse /riot http://127.0.0.1:8888/

        ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
        ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
</VirtualHost>

<VirtualHost *:443>
        SSLEngine on
        ServerName chat.[DOMAIN]

        AllowEncodedSlashes NoDecode

        #ProxyPass /riot http://127.0.0.1:8888/
        #ProxyPassReverse /riot http://127.0.0.1:8888/

        ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
        ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix

        #ProxyPreserveHost On
        #ProxyAddHeaders On
        #RequestHeader set X-Forwarded-Proto "https"

        SSLCertificateFile /etc/letsencrypt/live/chat.[DOMAIN]/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/chat.[DOMAIN]/privkey.pem
</VirtualHost>

<VirtualHost *:8448>
        SSLEngine on
        ServerName [DOMAIN]
        #ServerAlias chat.[DOMAIN]

        #ProxyPreserveHost On
        #ProxyAddHeaders On
        #RequestHeader set X-Forwarded-Proto "https"

        RemoteIPHeader X-Forwarded-For
        RemoteIPTrustedProxy 127.0.0.1

        AllowEncodedSlashes NoDecode
        ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
```

dimension-config:
```
# The web settings for the service (API and UI).
# It is best to have this run on localhost and use a reverse proxy to access Dimension.
web:
  port: 8184
  address: '127.0.0.1'

# Homeserver configuration
homeserver:
  name: "[DOMAIN]"

  clientServerUrl: "https://chat.[DOMAIN]"

admins:
  - "@riggo:chat.[DOMAIN]"

directly.
widgetBlacklist:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.0/8

database:
  # Where the database for Dimension is
  file: "/data/dimension.db"

  # Where to store misc information for the utility bot account.
  botData: "/data/bot.json"
# Display settings that apply to self-hosted go-neb instances
goneb:
  # The avatars to set for each bot. Usually these don't need to be changed, however if your homeserver
  # is not able to reach t2bot.io then you should specify your own here. To not use an avatar for a bot,
  # make the bot's avatar an empty string.
  avatars:
    giphy: "mxc://t2bot.io/c5eaab3ef0133c1a61d3c849026deb27"
    imgur: "mxc://t2bot.io/6749eaf2b302bb2188ae931b2eeb1513"
    github: "mxc://t2bot.io/905b64b3cd8e2347f91a60c5eb0832e1"
    wikipedia: "mxc://t2bot.io/7edfb54e9ad9e13fec0df22636feedf1"
    travisci: "mxc://t2bot.io/7f4703126906fab8bb27df34a17707a8"
    rss: "mxc://t2bot.io/aace4fcbd045f30afc1b4e5f0928f2f3"
    google: "mxc://t2bot.io/636ad10742b66c4729bf89881a505142"
    guggy: "mxc://t2bot.io/e7ef0ed0ba651aaf907655704f9a7526"
    echo: "mxc://t2bot.io/3407ff2db96b4e954fcbf2c6c0415a13"
    circleci: "mxc://t2bot.io/cf7d875845a82a6b21f5f66de78f6bee"
    jira: "mxc://t2bot.io/f4a38ebcc4280ba5b950163ca3e7c329"

# Custom sticker pack options.
# Largely based on https://github.com/turt2live/matrix-sticker-manager
stickers:
  # Whether or not to allow people to add custom sticker packs
  enabled: true

  # The sticker manager bot to promote
  stickerBot: "@stickers:t2bot.io"

  # The sticker manager URL to promote
  managerUrl: "https://stickers.t2bot.io"

# Settings for how Dimension is represented to the public
dimension:
  # This is where Dimension is accessible from clients. Be sure to set this
  # to your own Dimension instance.
  publicUrl: "https://dimension.[DOMAIN]"

# Settings for controlling how logging works
logging:
  file: logs/dimension.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5
```
