### ISSUE TITLE
Server don't accept accessToken

### ISSUE THREAD

**Issue by RezaBabapour** [turt2live/matrix-dimension#320]
Hi turt2live
I'm create `accessToken` using tutorial in this [link](https://t2bot.io/docs/access_tokens/) but when i try to start services i got this error: `errcode":"M_UNKNOWN_TOKEN","error":"Invalid macaroon passed."
,"soft_logout":false}`
Domain and SSL certificates are in haproxy. here is my docker-compose: 
```
version: "3.7"
services: 
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:v1.6.1
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/synapse/homeserver.yaml
    volumes:
      - /docker/compose/matrix/synapse:/data/synapse
      - /docker/data/matrix/slow-storage:/data/media_store
      - /docker/data/matrix/fast-storage:/data/uploads
    ports: 
      - "8008:8008"
    networks:
      - postgres
    depends_on: 
      - db
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "7"

  db:
    container_name: postgres
    image: postgres:12.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPass
      - POSTGRES_DB=synapse   
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /docker/data/matrix/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "7"

  riot-web:
    container_name: riot-web
    image: vectorim/riot-web:v1.5.6
    restart: unless-stopped
    volumes:
      - /docker/compose/matrix/riot-web:/app
    ports:
      - "5050:80"
    networks:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "7"
  
  dimension:
    container_name: dimension
    image: turt2live/matrix-dimension:travis_msc2140-tos    
    ports:
      - "127.0.0.1:8184:8184"
    volumes:
      - /docker/compose/matrix/dimension:/data

networks:
  postgres:
    driver: bridge
```
Riot and Synapse are working but Integration server stops after that error message.
here is my dimension config file:
```
web:
  port: 8184
  address: '0.0.0.0'
homeserver:
  name: "serverIP:8008"
  clientSercerUrl: "serverIP:5050"
  accessToken: "Long Token"
  federationUrl: "serverIP:8008"

admins:
  - "@admin:myServer.com"

widgetBlacklist:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.0/8

database:
  file: "/data/dimension.db"
  botData: "/data/bot.json"

dimension:
  publicUrl: "serverIP:8184"

logging:
  file: logs/dimension.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 5242880
    count: 5
```
Have you any Idea about what is wrong with my configuration?
