### ISSUE TITLE
npm error 1 ELIFECYCLE starting app

### ISSUE THREAD

**Issue by r4a5a88** [turt2live/matrix-dimension#331]
Hello 

today I installed dimension a ubuntu 18.04 machine with npm 6 and nodejs 10.
I run ist as a stand alone server. my matrix is on another server
In Theory it should work. In practice it does not

this is my config 

```

 web:
   port: 8184
   address: 'IP'
 
 
 homeserver:
  name: "NAME"

 
   clientServerUrl: "URL"

  accessToken: "heicumedia"
admins:
- "USER" 
 
 widgetBlacklist:
   - 10.0.0.0/8
   - 172.16.0.0/12
   - 192.168.0.0/16
   - 127.0.0.0/8
 
 database:
   
   file: "dimension.db"
 
   botData: "dimension.bot.json" 
 
 goneb:
   
   avatars:
     giphy: "mxc://t2bot.io/c5eaab3ef0133c1a61d3c849026deb27"
     imgur: "mxc://t2bot.io/6749eaf2b302bb2188ae931b2eeb1513"
     github: "mxc://t2bot.io/905b64b3cd8e2347f91a60c5eb0832e1"
     wikipedia: "mxc://t2bot.io/7edfb54e9ad9e13fec0df22636feedf1"
     travisci: "mxc://t2bot.io/7f4703126906fab8bb27df34a17707a8"
     rss: "mxc://t2bot.io/aace4fcbd045f30afc1b4e5f0928f2f3"
     google: "mxc://t2bot.io/636ad10742b66c4729bf89881a505142"
     guggy: "mxc://t2bot.io/e7ef0ed0ba651aaf907655704f9a7526"
     echo: "mxc://t2bot.io/3407ff2db96b4e954fcbf2c6c0415a13"
     circleci: "mxc://t2bot.io/cf7d875845a82a6b21f5f66de78f6bee"
   jira: "mxc://t2bot.io/f4a38ebcc4280ba5b950163ca3e7c329"
 
 telegram:
 
   botToken: "YourTokenHere"
 
 stickers:
   
enabled: true 
stickerBot: "@stickers:t2bot.io"
 
managerUrl: "https://stickers.t2bot.io"

dimension:
 
   publicUrl: "URL" 
 logging:
   file: logs/dimension.log
   console: true
   consoleLevel: info
   fileLevel: verbose
   rotate:
     size: 52428800 #
    count: 5`
```
This is the log 

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start:app' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart:app', 'start:app', 'poststart:app' ]
5 info lifecycle matrix-dimension@1.0.0~prestart:app: matrix-dimension@1.0.0
6 info lifecycle matrix-dimension@1.0.0~start:app: matrix-dimension@1.0.0
7 verbose lifecycle matrix-dimension@1.0.0~start:app: unsafe-perm in lifecycle true
8 verbose lifecycle matrix-dimension@1.0.0~start:app: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/matrix-dimension/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle matrix-dimension@1.0.0~start:app: CWD: /opt/matrix-dimension
10 silly lifecycle matrix-dimension@1.0.0~start:app: Args: [ '-c', 'npm run-script build && node build/app/index.js' ]
11 silly lifecycle matrix-dimension@1.0.0~start:app: Returned: code: 1  signal: null
12 info lifecycle matrix-dimension@1.0.0~start:app: Failed to exec start:app script
13 verbose stack Error: matrix-dimension@1.0.0 start:app: `npm run-script build && node build/app/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid matrix-dimension@1.0.0
15 verbose cwd /opt/matrix-dimension
16 verbose Linux 4.15.18-20-pve
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start:app"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error matrix-dimension@1.0.0 start:app: `npm run-script build && node build/app/index.js`
22 error Exit status 1
23 error Failed at the matrix-dimension@1.0.0 start:app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

How can I fix it ? What can I do ?
