### ISSUE TITLE
Not seeing bots and bridges

### ISSUE THREAD

**Issue by quenenni** [turt2live/matrix-dimension#333]
Hello,

I successfully installed dimension integrator on our matrix-synapse server.

All seems working well except I only see the widgets and stickers sections, but not the bots and bridges.

I did the changes in the config.json file from our Riot to use our dimension integrator:
```
    "integrations_ui_url": "https://xxx.yyy.zzz/riot",
    "integrations_rest_url": "https://xxx.yyy.zzz/api/v1/scalar",
    "integrations_widgets_urls": ["https://xxx.yyy.zzz/widgets"],
    "integrations_jitsi_widget_url": "https://xxx.yyy.zzz/widgets/jitsi",
```

Also the ones in dimension config file:
```
database:
  # Where the database for Dimension is
  file: "dimension.db"

  # Where to store misc information for the utility bot account.
  botData: "dimension.bot.json"
```

Logs looks good, no error found.

I looked through the setting section of the integrator, but no option for that.

Also, I noticed I have Riot-web v1.5.3, from last November. Too old?

Is there something else to configure to access them?
Or are they only available when using dimension.t2bot.io server?

Thank you

----
Debian buster / nginx 1.14.2-2+deb10u1 / matrix-synapse 1.11.1-1~bpo10+1
