### ISSUE TITLE
Unfederated matrix setup not working

### ISSUE THREAD

**Issue by d3473r** [turt2live/matrix-dimension#399]
Hi, 

I'm unable to connect to an unfederated matrix instance, please explain the configuration in an unfederated environment., especially the federationUrl setting.

## To Reproduce

Step by step instructions to reproduce the behavior:

1. Run matrix unfederated on `matrix.example.com`, `openid` is enabled

```
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client, openid]
        compress: false
```

2. Deploy the `turt2live/matrix-dimension` docker image in the same kubernetes namespace and configure a bot
```
web:
  port: 8184
  address: '0.0.0.0'
  name: "matrix.example.com"
  clientServerUrl: "https://matrix.example.com"
  federationUrl: "matrix:8008"
  accessToken: "XXX"
```

`[BotSdk-MatrixLiteClient (REQ-1 RESP-H200)] {"user_id":"@dimension:example.com"}`

`matrix:8008` is reachable from the dimension container
```
~ # curl matrix:8008
<html>
    <head>
        <meta http-equiv="refresh" content="0;URL=/_matrix/static">
    </head>
    <body bgcolor="#FFFFFF" text="#000000">
    <a href="/_matrix/static">click here</a>
    </body>
</html>
```

## Expected behavior
Dimension should connect to matrix via `matrix:8008`

## Describe the bug
Dimension tries to connect to matrix via `example.com`
```
Feb-24-2021 10:52:23.024 +00:00 info [MemoryCache] Creating a new cache for namespace: federation
Feb-24-2021 10:52:23.074 +00:00 warn [matrix] Non-fatal error looking up .well-known for example.com
```

and a little bit later:
```
Feb-24-2021 10:54:30.401 +00:00 error [matrix] Error calling /_matrix/federation/v1/openid/userinfo
Feb-24-2021 10:54:30.402 +00:00 error [matrix] connect ETIMEDOUT XXX.XXX.XXX.XXX:8448
Error: connect ETIMEDOUT XXX.XXX.XXX.XXX:8448
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Error: connect ETIMEDOUT 188.40.30.106:8448
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
```

XXX.XXX.XXX.XXX is the IP of example.com

## Details

It looks like the `federationUrl: "matrix:8008"` is not used, instead dimension tries the default `server_name` server [(delegation)](https://github.com/matrix-org/synapse/blob/master/docs/delegate.md)

**Screenshots**
<img width="246" alt="2021-02-24 12_09_53-Element _ notes" src="https://user-images.githubusercontent.com/10356892/108992728-ec367d80-7699-11eb-81ad-4b84769992cd.png">

Regards,
Fabian
