### ISSUE TITLE
BigBlueButton Widget can't join conference possible bug?

### ISSUE THREAD

**Issue by kubax** [turt2live/matrix-dimension#475]
When i try to add a BigBlueButton conference to a room, and try joining it, this error occurs on the Dimension log output (docker)

Looks like $conferenceUrl is somehow put as text, insted of the value of the variabe into the Url that Element tries to open.

Is there something i should have configured and didn't or is this a bug?

```
Wed, 23 Feb 2022 16:13:17 GMT [INFO] [Webserver] Incoming request: GET /widgets/bigbluebutton?conferenceUrl=$conferenceUrl&displayName=Tobias&avatarUrl=https%3A%2F%2Fxxxxxxxxxx%2F_matrix%2Fmedia%2Fr0%2Fdownload%2Fxxxxxxxxxxx%2FUnyvOexxxxxxxxxAbpbqwzmF&userId=%40xxxxxxxx%3Axxxxxxxxxxxx&widgetId=dimension-bigbluebutton-1645631958782&parentUrl=vector%3A%2F%2Fvector%2Fwebapp%2F
Wed, 23 Feb 2022 16:13:24 GMT [INFO] [Webserver] Incoming request: GET /api/v1/dimension/bigbluebutton/join?greenlightUrl=%24conferenceUrl&fullName=Tobias%20(%40xxxxxxx%3Axxxxxxxxxx)&scalar_token=redacted
TypeError [ERR_INVALID_URL]: Invalid URL: $conferenceUrl
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at DimensionBigBlueButtonService.<anonymous> (/home/node/matrix-dimension/build/app/api/dimension/DimensionBigBlueButtonService.js:113:41)
    at Generator.next (<anonymous>)
    at /home/node/matrix-dimension/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/node/matrix-dimension/node_modules/tslib/tslib.js:106:16)
    at DimensionBigBlueButtonService.join (/home/node/matrix-dimension/build/app/api/dimension/DimensionBigBlueButtonService.js:111:24)
    at ServiceInvoker.<anonymous> (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:152:41)
    at step (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:33:23)
    at Object.next (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:14:53)
    at /home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:4:12)
    at ServiceInvoker.callTargetEndPoint (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:133:16)
    at ServiceInvoker.<anonymous> (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:61:51)
    at step (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:33:23)
    at Object.next (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:14:53)
    at /home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:4:12)
    at ServiceInvoker.callService (/home/node/matrix-dimension/node_modules/typescript-rest/dist/server/service-invoker.js:55:16)
```

**Comment by yoitcc** [comment]
I do get the exact same error, when trying to "Join Conference".

I installed dimension (today) with https://github.com/spantaleev/matrix-docker-ansible-deploy, using the following configuration for the playbook:
```
##BigBlueButton Dimension Widget Configuration
matrix_dimension_configuration_extension_yaml: |
  bigbluebutton:
  # The full base URL of the API of your BigBlueButton instance. The API is
  # used to create and join meetings.
  apiBaseUrl: "https://bbb.example.org/bigbluebutton/api"
  # The "shared secret" of your BigBlueButton instance. This is used to
  # authenticate to the API above.
  sharedSecret: "PUBLICISNOSECRET"
  # The title for BigBlueButton widgets that are generated by Dimension.
  widgetName: "BigBlueButton BlaBla"
  # The subtitle for BigBlueButton widgets that are generated by Dimension.
  widgetTitle: "Join the conference"
  # The avatar for BigBlueButton widgets that are generated by Dimension.
  # Usually this doen't need to be changed, however if your homeserver
  # is not able to reach t2bot.io then you should specify your own here.
  widgetAvatarUrl: "mxc://t2bot.io/be1650140620d8bb61a8cf5baeb05f24a734434c"
```
which produces the following section in the dimension config.yaml:
```
bigbluebutton:
  apiBaseUrl: https://bbb.example.org/bigbluebutton/api
  sharedSecret: PUBLICISNOSECRET
  widgetAvatarUrl: mxc://t2bot.io/be1650140620d8bb61a8cf5baeb05f24a734434c
  widgetName: BigBlueButton BlaBla
  widgetTitle: Join the conference
```
That looks pretty correct compared to https://github.com/turt2live/matrix-dimension/blob/master/config/default.yaml
Are there any other places bigbluebutton needs configuration?
