### ISSUE TITLE
Problem with the Installation

### ISSUE THREAD

**Issue by golli1337** [turt2live/matrix-dimension#480]
When I install Dimension using Docker and the provided guide I get this Error.

```
[INFO] [Webserver] API and UI listening on 0.0.0.0:8184
[DEBUG] [MatrixHttpClient (REQ-1)] GET https://matrix.example.com/_matrix/client/r0/account/whoami
[ERROR] [MatrixHttpClient (REQ-1)] Error: connect ECONNREFUSED 127.0.1.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
        errno: -111,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.1.1',
        port: 443
}
Error: connect ECONNREFUSED 127.0.1.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
        errno: -111,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.1.1',
        port: 443
}
```

I tried using just docker run like in the guide but since it results in the same error as my docker-compose file, i'd rather use that.

docker-compose.yml
```
services:
  dimension:
    image: turt2live/matrix-dimension
    ports:
      - "8184:8184"
    volumes:
      - /srv/matrix/dimension/data:/data

```
and my data/config.yaml
```

web:
  port: 8184
  address: 0.0.0.0
homeserver:
  name: matrix.example.com
  clientServerUrl: https://matrix.example.com
  federationUrl: https://matrix-federation.example.com
  accessToken: ****
admins:
- '@name:example.com'
database:
  file: /data/dimension.db
  botData: /data/bot.json
dimension:
  publicUrl: https://matrix-dimension.example.com

```
I also use a nginx reverse proxy to make matrix-dimension.example.com matrix-federation.example.com and matrix.example.com available via the respective ports.
Any help would be greatly appreciated.
